title: Something to say -  Còn chút gì để gáy
description: Something to say -  Còn chút gì để gáy
author: Đỗ Minh Tùng
github: https://github.com/notikki
about: I am coder. I like Javascript and Vuejs.
disqus_shortname: ilikenode

enableTags: true
tagarray: []

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/notikki"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/notikki"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/notikki"

share:
  twitter_username: notikki

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://notikki.github.io"
baseurl: ""
paginate: 8
per_page: 8
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
